name: yole_mobile
description: "YOLE Mobile Application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Core icons
  cupertino_icons: ^1.0.8

  # State management
  flutter_riverpod: ^2.6.1

  # Contacts + permissions
  flutter_contacts: ^1.1.9+2
  permission_handler: ^11.3.1

  # Localization support
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # Splash screen
  flutter_native_splash: ^2.4.6

  # Local storage
  shared_preferences: ^2.2.2
  
  # Image picking for KYC
  image_picker: ^1.0.4

  # PesaPal API integration
  webview_flutter: ^4.4.4  # For PesaPal iframe
  http: ^1.1.2              # For API calls
  crypto: ^3.0.3            # For authentication
  url_launcher: ^6.2.2      # For opening PesaPal in browser
  
  # Secure storage for tokens
  flutter_secure_storage: ^9.0.0
  
  # SVG rendering for pixel-perfect logos
  flutter_svg: ^2.0.9
  
  # Cached network images for better performance
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#121212"
  android_12:
    color: "#FFFFFF"
    color_dark: "#121212"
